name: Scala Bootcamp Homeworks CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - id: checkout
        name: Checkout
        uses: actions/checkout@v2

      - id: detect_changes
        name: Detect changes
        uses: zattoo/recognition@v2
        with:
          Domains: '{"01": ["01/scala"], "02": ["02/scala"], "03": ["03/scala"], "04": ["04/scala"], "05": ["05/scala"],
                     "06": ["06/scala"], "08": ["08/scala"], "10": ["10/scala"],
                     "11": ["11/scala"], "12": ["12/scala"], "13": ["13/scala"], "14": ["14/scala"], "15": ["15/scala"],
                     "16": ["16/scala"], "17": ["17/scala"], "18": ["18/scala"], "19": ["19/scala"], "20": ["20/scala"],
                     "21": ["21/scala"], "22": ["22/scala"], "23": ["23/scala"], "24": ["24/scala"]}' # name : path
          token: ${{github.token}}

      - id: read_projects
        name: Read projects
        uses: Stockopedia/action-run-on-list@v1
        with:
          list: ${{ steps.detect_changes.outputs.projects }}
          command: |
            echo "detected changes in $item" 
            # doing >> $GITHUB_ENV doesn't work here ☹️
            # if more than one project level change is detected, the output will be the last one here 😬
            echo "::set-output name=project_name::$item"

      - id: eval_project_name
        name: Evaluate project name
        if: "${{ steps.read_projects.outputs.project_name != '' }}"
        run: echo ${{ steps.read_projects.outputs.project_name }}

      - id: run_tests
        name: Run tests
        working-directory: ${{ steps.read_projects.outputs.project_name }}/scala
        if: "${{ steps.read_projects.outputs.project_name != '' }}"
        run: sbt coverage test

      # - id: create_coverage_report
      #   name: Create coverage report
      #   working-directory: ${{ steps.read_projects.outputs.project_name }}/scala
      #   if: "${{ steps.read_projects.outputs.project_name != '' }}"
      #   run: sbt coverageReport

      # - id: upload_coverage_report
      #   name: Upload coverage report to Codecov
      #   if: "${{ steps.read_projects.outputs.project_name != '' }}"
      #   uses: codecov/codecov-action@v1